FROM python:3.7.9
ENV SECRET="docker change me"
LABEL maintainer_name="Omar Magdy"
COPY requirements.txt ../service_hello_world/requirements.txt
RUN pip install -r requirements.txt
COPY . ../service_hello_world
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_APP=app
ENV FLASK_ENV=development
ENV FLASK_DEBUG=0
EXPOSE 5000
CMD ["flask", "run"]